version: "3"
services:
  backend:
    image: backend-image
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL='mongodb+srv://arnab0321:bH1Ttke9EZBmYClg@cluster0.dehf4yw.mongodb.net/?retryWrites=true&w=majority'
    # Add any additional configuration or volumes as needed

  frontend:
    image: frontend-image
    build:
      context: ./client
    ports:
      - "80:80"
