name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Client Dependencies
      working-directory: ./client
      run: |
        npm install

    - name: Build and Test Client
      working-directory: ./client
      run: |
        npm run build
        npm test

  server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Server Dependencies
      working-directory: ./server
      run: |
        npm install

    - name: Test Server
      working-directory: ./server
      run: |
        npm test

